app:
  name: "douYin_app"
  mode: "dev"
  port: 8080
  version: "v0.1.1"
  start_time: "2020-07-01"
  machine_id: 1
log:
  level: "debug"
  filename: "douYin_app.log"
  max_size: 2000
  max_age: 30
  max_backups: 7

mysql:
  host: "8.130.40.129"
  port: 3306
  user: "root"
  password: "S21070078"
  dbname: "douyin"
  max_open_connections: 200
  max_idle_connections: 10
  max_
redis:
  host: "8.130.40.129"
  port: 6379
  password: "S21070078"
  db: 0
  pool_size: 100
  expire_time_long: 86400000000000
video:
  count: 4